### PR TITLE
fix: send test result when scenario is retried

### LINKED ISSUE #7: Test Results excluded from Xray export when using Scenario level retry()
## Context
I am finding that for some builds a test does not get added to the export. When this problem occurs I notice console messages printed around the test such as:
> TypeError: Cannot read properties of undefined ....

## Actual Behavior
When the problem occurs the follow console messages appear right near the test that is being executed.
>TypeError: Cannot read properties of undefined (reading 'toString')
>TypeError: Cannot read properties of undefined (reading 'toUpperCase')
>TypeError: Cannot read properties of undefined (reading 'every')

In this example the single test passes, and the **TypeError**s are displayed in the console and then the "0 test validation error" is thrown and fails the build. _(BTW I was planning on submitting a question around the behaviour of this validation error as it fails the build.  Not sure if the that is preferred. However this other issue is more pressing)_

```
CodeceptJS v3.4.1 #StandWithUkraine
Using test root "/builds/e2e-tests"

Three page checkout --
TypeError: Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
  ✔ Checkout with matching Canadian shipping and billing addresses (GUEST USER) @TEST_PXP-858 in 73196ms
TypeError: Cannot read properties of undefined (reading 'every')

  OK  | 1 passed   // 5m
Send results to JIRA : 
{
  "info": {
    "project": "PXP",
    "summary": "E2E Test Execution in Branch link-taxes-tests",
    "description": "E2E Test execution automatically created from Gitlab ",
    "version": "",
    "revision": "",
    "startDate": "2023-08-10T18:10:07+00:00",
    "finishDate": "2023-08-10T18:15:13+00:00",
    "testPlanKey": "PXP-760",
    "testEnvironments": []
  },
  "tests": []
}
Error in xray execute import body, please refer to the developer. 
Reason : 
 [
  ValidationError {
    path: [ 'tests' ],
    property: 'instance.tests',
    message: 'does not meet minimum length of 1',
    schema: { type: 'array', items: [Object], minItems: 1 },
    instance: [],
    name: 'minItems',
    argument: 1,
    stack: 'instance.tests does not meet minimum length of 1'
  }
]
```

## Steps to Reproduce the Problem
 This problem seems to be intermittent and difficult to reproduce.  

* The build runs on Gitlab.
* Node version: v18.17.0
* CodeceptJS 3.4.1 with Typescript

Seems that the three missing properties exist in `index.js`. 
Not sure why the `test` object would not be available after the event is fired. 
```
event.dispatcher.on(event.test.after, function (test) {
        recorder.add('Get test results', function () {
            //Get test status
            const status = test.state.toUpperCase();

            let test_contains_examples = false;
            let test_contains_iterations = false;

            //Get tag from test, this tag will be used as a testKey in the api to link the test execution with a JIRA test (if createNewJiraTest is false)
            test.tags.every(tag => {
                if (tag.toString().includes("@TEST_")) {
                    test_key = tag.split("@TEST_")[1];
                    return false;
                } else {
                    test_key = "no_xray_tag";
                }
                return true;
            });

        ....
```

### PR DESCRIPTION
**Pull request by saadichouaib**
Fixes https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/issues/7

### Context

Actually, when a test is retried, codeceptjs returns a different `test` object.

For instance, to get the status of a test we use `test.state`, but when test is a retry we should get it through `test._retriedTest.state`.

This PR fixes this issue so only the last result of a retried scenario is sent to Xray.

### CODE REVIEW

**Comment by saadichouaib** [comment]
This will fix https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/issues/7.

**Scope :**
- Scenario fail with retry
- Scenario fail without retry
- Scenario fail with screenshots
- Check the error message sent to Xray

@jmychasiw , could you do some exploratory please ?

**Comment by jmychasiw** [comment]
As per comment from @saadichouaib and further investigation, it is revealed that 
This PR does not currently cover cases when the source of the error is created outside of a CodeceptJS helper.

I confirmed this by setting up other helpers such as `REST` and `FileSystem`.  In each case when the error is thrown from a direct `assert`  it will error on `TypeError: Cannot read properties of undefined (reading 'toUpperCase')` as opposed to when the error is thrown from a Helper.

This is also verified by wrapping the node assert in new Codecept Helper:

```
const assert = require('assert');

class AssertHelper extends Helper {
    failTest(message: string) {
        assert.fail(message);
    }
}

export = AssertHelper;
```
Configure:
```
 helpers: {
    FileSystem: {},
    REST: {},
    AssertHelper: {
      require: './helpers/assert_helper.ts'
    }
```

# Test with assert wrapped in the CodeceptJS helper

```
const assert = require('assert');

Feature('Demo Testing')

Scenario('Scenario Test One', ({ I }) => {
    // assert.fail("fail using direct assert");
    I.failTest('test is failed from a helper');
}).tag('TEST_QAT3-370').retry(3);

Scenario('Scenario Test Two', ({ I }) => {
    assert.equal(true, true);
}).tag('TEST_QAT3-374');
```

```
 xray-plugin-debug git:(main) ✗ npx codeceptjs run --steps
CodeceptJS v3.5.4 #StandWithUkraine

Demo Testing --
  Scenario Test One @TEST_QAT3-370
    I fail test "test is failed from a helper"
    I fail test "test is failed from a helper"
    I fail test "test is failed from a helper"
    I fail test "test is failed from a helper"
  ✖ Scenario Test One @TEST_QAT3-370 in 727ms
  Scenario Test Two @TEST_QAT3-374
  ✔ OK in 1ms


-- FAILURES:

  1) Demo Testing
       Scenario Test One @TEST_QAT3-370:
     test is failed from a helper
      at AssertHelper.failTest (helpers/assert_helper.ts:5:16)
      at Step.run (node_modules/codeceptjs/lib/step.js:122:47)
      at /Users/../Workspace/Xray/xray-plugin-debug/node_modules/codeceptjs/lib/actor.js:135:23

  FAIL  | 1 passed, 1 failed   // 3s
Run with --verbose flag to see complete NodeJS stacktrace
Send results to JIRA :
{
  "info": {
    "project": "QAT3",
    "summary": "Test Execution From local machine",
    "description": "Test execution automatically created from Build XYZ!",
    "version": "",
    "revision": "",
    "startDate": "2023-10-10T14:21:59-05:00",
    "finishDate": "2023-10-10T14:22:02-05:00",
    "testPlanKey": "QAT3-369",
    "testEnvironments": [
      "browser-chrome",
      "platform-magento-one"
    ]
  },
  "tests": [
    {
      "testKey": "QAT3-370",
      "start": "2023-10-10T14:22:01-05:00",
      "finish": "2023-10-10T14:22:02-05:00",
      "comment": "AssertionError [ERR_ASSERTION]: test is failed from a helper",
      "executedBy": "",
      "assignee": "",
      "status": "FAILED",
      "defects": [],
      "evidence": [],
      "customFields": []
    },
    {
      "testKey": "QAT3-374",
      "start": "2023-10-10T14:22:02-05:00",
      "finish": "2023-10-10T14:22:02-05:00",
      "comment": "Test passed successfully",
      "executedBy": "",
      "assignee": "",
      "status": "PASSED",
      "defects": [],
      "evidence": [],
      "customFields": []
    }
  ]
}
```

# Test with using assert directly from test

```
Scenario('Scenario Test One', ({ I }) => {
    assert.fail("fail using direct assert");
    I.failTest('test is failed from a helper');
}).tag('TEST_QAT3-370').retry(3);

Scenario('Scenario Test Two', ({ I }) => {
    assert.equal(true, true);
}).tag('TEST_QAT3-374');
```
```
xray-plugin-debug git:(main) ✗ npx codeceptjs run --steps
CodeceptJS v3.5.4 #StandWithUkraine

Demo Testing --
  Scenario Test One @TEST_QAT3-370
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
  ✖ Scenario Test One @TEST_QAT3-370 in 0ms
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
  Scenario Test Two @TEST_QAT3-374
  ✔ OK in 1ms


-- FAILURES:

  1) Demo Testing
       Scenario Test One @TEST_QAT3-370:
     fail using direct assert
      at Test.<anonymous> (sample_test.ts:6:12)
      at Context.test.fn (node_modules/codeceptjs/lib/scenario.js:92:14)




  FAIL  | 1 passed, 1 failed   // 24ms
Run with --verbose flag to see complete NodeJS stacktrace
Send results to JIRA :
{
  "info": {
    "project": "QAT3",
    "summary": "Test Execution From local machine",
    "description": "Test execution automatically created from Build XYZ!",
    "version": "",
    "revision": "",
    "startDate": "2023-10-10T14:24:53-05:00",
    "finishDate": "2023-10-10T14:24:53-05:00",
    "testPlanKey": "QAT3-369",
    "testEnvironments": [
      "browser-chrome",
      "platform-magento-one"
    ]
  },
  "tests": [
    {
      "testKey": "QAT3-374",
      "start": "2023-10-10T14:24:53-05:00",
      "finish": "2023-10-10T14:24:53-05:00",
      "comment": "Test passed successfully",
      "executedBy": "",
      "assignee": "",
      "status": "PASSED",
      "defects": [],
      "evidence": [],
      "customFields": []
    }
  ]
}
```

File: index.js
Comment (jmychasiw) [inline index.js:1]: Including the count of exported tests would be helpful:

From:
```
if (response.status === 200) output.print(`\n> Tests results were sent to XRAY on TestExecution : ${response.data.key}\n`);
```

To something like:
```
 if (response.status === 200) output.print(`\n> Test results from ${import_execution_data.tests.length} tests were sent to XRAY on TestExecution : ${response.data.key}\n`);

```

File: lib/common.js [hunk 1]
```diff
@@ -3,29 +3,35 @@ const fs = require('fs');
...
+        if (test_state === "passed") {
             tests_results.push({
                 title: test.title,
                 status: "PASSED",
                 comment: "Test passed successfully",
                 test_key: test_key,
                 start: moment(test.startedAt).format(),
                 finish: moment().format(),
-                id: test.id,
+                id: test?.uid,
```
Comment (jmychasiw) [inline lib/common.js:19]: Curious why this change?  was it related to this fix?

**Review by jmychasiw — CHANGES_REQUESTED** [review]

File: lib/common.js (hunk 1 above)
Comment (saadichouaib) [reply lib/common.js:19]: not related, just for testing purpose 👍

Comment (saadichouaib) [reply lib/common.js:19]: Done on [229dd1f](https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/pull/10/commits/229dd1fb14bc55b14e912cf93c5842da41f7952d) 👍

File: index.js
Comment (saadichouaib) [reply index.js:1]: Done on [229dd1f](https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/pull/10/commits/229dd1fb14bc55b14e912cf93c5842da41f7952d) 👍

**Comment by saadichouaib** [comment]
@jmychasiw
I just pushed a solution that handle all those scenarios.
Keep me infoirmed after your tests 👍
